import type { BadgeDefinition, ChallengeDefinition, RewardDefinition, TeamPreview } from "./types";

export const REWARD_CATALOG: RewardDefinition[] = [
  {
    id: "reward-badge-only",
    kind: "badge_only",
    title: "Recognition unlock",
    description: "Unlock the badge and celebrate the momentum. Reward fulfillment can layer in later.",
  },
];

export const BADGE_CATALOG: BadgeDefinition[] = [
  {
    id: "badge-first-walk",
    title: "Mindful Steps",
    description: "Your first intentional outside reset is in the books.",
    category: "milestone",
    rarity: "common",
    accent: "forest",
    artKey: "mindful-steps",
    unlockChallengeId: "challenge-first-walk",
  },
  {
    id: "badge-7-day-streak",
    title: "7 Day Streak",
    description: "Seven steady days of showing up.",
    category: "streak",
    rarity: "rare",
    accent: "forest",
    artKey: "7-day-streak",
    unlockChallengeId: "challenge-7-day-streak",
  },
  {
    id: "badge-sunrise-walker",
    title: "Sunrise Walker",
    description: "Catch five morning starts while the day is still waking up.",
    category: "time_of_day",
    rarity: "rare",
    accent: "sunrise",
    artKey: "sunrise-walker",
    unlockChallengeId: "challenge-sunrise-five",
  },
  {
    id: "badge-weekend-warrior",
    title: "Weekend Warrior",
    description: "Keep the habit alive through your weekends too.",
    category: "community",
    rarity: "common",
    accent: "sunrise",
    artKey: "weekend-warrior",
    unlockChallengeId: "challenge-weekend-warrior",
  },
  {
    id: "badge-trailblazer",
    title: "Trailblazer",
    description: "Build up a strong base of hikes and longer routes.",
    category: "milestone",
    rarity: "rare",
    accent: "forest",
    artKey: "trailblazer",
    unlockChallengeId: "challenge-trailblazer",
  },
  {
    id: "badge-comeback",
    title: "Comeback",
    description: "Find your rhythm again after time away.",
    category: "recovery",
    rarity: "common",
    accent: "sunrise",
    artKey: "comeback",
    unlockChallengeId: "challenge-comeback",
  },
  {
    id: "badge-100-mile-club",
    title: "100 Mile Club",
    description: "A huge long-term milestone built from consistent steps.",
    category: "milestone",
    rarity: "legendary",
    accent: "forest",
    artKey: "100-mile-club",
    unlockChallengeId: "challenge-100-mile-club",
  },
  {
    id: "badge-daily-outside",
    title: "Daily Outside",
    description: "A steadier daily rhythm that turns outside time into a real ritual.",
    category: "streak",
    rarity: "rare",
    accent: "forest",
    artKey: "daily-outside",
    availability: "coming_soon",
  },
  {
    id: "badge-evening-walk",
    title: "Evening Walk",
    description: "A calmer close to the day, marked by intentional evening miles.",
    category: "time_of_day",
    rarity: "common",
    accent: "sunrise",
    artKey: "evening-walk",
    availability: "coming_soon",
  },
  {
    id: "badge-park-loop",
    title: "Park Loop",
    description: "A familiar green loop that becomes part of your reset routine.",
    category: "community",
    rarity: "common",
    accent: "forest",
    artKey: "park-loop",
    availability: "coming_soon",
  },
  {
    id: "badge-quiet-miles",
    title: "Quiet Miles",
    description: "Longer stretches of unhurried movement and quieter headspace.",
    category: "recovery",
    rarity: "rare",
    accent: "forest",
    artKey: "quiet-miles",
    availability: "coming_soon",
  },
  {
    id: "badge-sunrise-reset",
    title: "Sunrise Reset",
    description: "An early reset that starts before the day gets loud.",
    category: "time_of_day",
    rarity: "rare",
    accent: "sunrise",
    artKey: "sunrise-reset",
    availability: "coming_soon",
  },
  {
    id: "badge-trail-explorer",
    title: "Trail Explorer",
    description: "For the walker who keeps choosing new scenery and a little more wonder.",
    category: "milestone",
    rarity: "rare",
    accent: "forest",
    artKey: "trail-explorer",
    availability: "coming_soon",
  },
  {
    id: "badge-weekend-trail",
    title: "Weekend Trail",
    description: "A slower weekend route with enough space to wander and reset.",
    category: "community",
    rarity: "common",
    accent: "sunrise",
    artKey: "weekend-trail",
    availability: "coming_soon",
  },
];

export const CHALLENGE_CATALOG: ChallengeDefinition[] = [
  {
    id: "challenge-first-walk",
    slug: "first-walk",
    title: "First Walk",
    shortTitle: "First walk",
    description: "Log your first walk or hike outside.",
    type: "milestone",
    metric: "sessions",
    goal: 1,
    window: "all_time",
    cadence: "evergreen",
    audience: "personal",
    badgeId: "badge-first-walk",
    rewardId: "reward-badge-only",
    highlight: "forest",
  },
  {
    id: "challenge-7-day-streak",
    slug: "streak-7-days",
    title: "7 Day Streak",
    shortTitle: "7-day streak",
    description: "Build a seven-day run of steady resets.",
    type: "streak",
    metric: "current_streak_days",
    goal: 7,
    window: "rolling_7d",
    cadence: "evergreen",
    audience: "personal",
    badgeId: "badge-7-day-streak",
    rewardId: "reward-badge-only",
    highlight: "forest",
  },
  {
    id: "challenge-consistency-club",
    slug: "consistency-club",
    title: "Consistency Club",
    shortTitle: "4 of 7 days",
    description: "Hit four active days this week to keep the habit light but real.",
    type: "completion_percentage",
    metric: "days_completed",
    goal: 4,
    window: "weekly",
    cadence: "evergreen",
    audience: "personal",
    highlight: "forest",
  },
  {
    id: "challenge-sunrise-five",
    slug: "sunrise-five",
    title: "Sunrise Walker",
    shortTitle: "5 sunrise walks",
    description: "Collect five sunrise starts.",
    type: "time_of_day",
    metric: "sunrise_sessions",
    goal: 5,
    window: "all_time",
    cadence: "evergreen",
    audience: "personal",
    badgeId: "badge-sunrise-walker",
    rewardId: "reward-badge-only",
    highlight: "sunrise",
  },
  {
    id: "challenge-weekend-warrior",
    slug: "weekend-warrior",
    title: "Weekend Warrior",
    shortTitle: "4 weekend sessions",
    description: "Make weekends part of your rhythm too.",
    type: "time_of_day",
    metric: "weekend_sessions",
    goal: 4,
    window: "monthly",
    cadence: "evergreen",
    audience: "personal",
    badgeId: "badge-weekend-warrior",
    rewardId: "reward-badge-only",
    highlight: "sunrise",
  },
  {
    id: "challenge-trailblazer",
    slug: "trailblazer",
    title: "Trailblazer",
    shortTitle: "8 hikes",
    description: "Complete eight hikes to deepen the outdoor habit.",
    type: "milestone",
    metric: "hike_sessions",
    goal: 8,
    window: "all_time",
    cadence: "evergreen",
    audience: "personal",
    badgeId: "badge-trailblazer",
    rewardId: "reward-badge-only",
    highlight: "forest",
  },
  {
    id: "challenge-comeback",
    slug: "comeback",
    title: "Comeback",
    shortTitle: "3 active days",
    description: "Find your way back with three active days this week.",
    type: "completion_percentage",
    metric: "days_completed",
    goal: 3,
    window: "weekly",
    cadence: "evergreen",
    audience: "personal",
    badgeId: "badge-comeback",
    rewardId: "reward-badge-only",
    highlight: "sunrise",
  },
  {
    id: "challenge-100-mile-club",
    slug: "100-mile-club",
    title: "100 Mile Club",
    shortTitle: "100 miles",
    description: "Reach 100 total miles over time.",
    type: "milestone",
    metric: "distance_m",
    goal: 160934,
    window: "all_time",
    cadence: "evergreen",
    audience: "personal",
    badgeId: "badge-100-mile-club",
    rewardId: "reward-badge-only",
    highlight: "forest",
    isPremium: true,
  },
];

export const TEAM_MVP_PREVIEW: TeamPreview = {
  companyName: "Step Outside Workplace",
  teamName: "Mindful Movers",
  inviteCodeHint: "Use invite codes to join a company or default team in the MVP.",
  activeChallengeTitle: "Company Reset Week",
  leaderboard: [
    { id: "member-1", name: "Avery", streakDays: 6, activeDays: 4 },
    { id: "member-2", name: "Jordan", streakDays: 5, activeDays: 4 },
    { id: "member-3", name: "Taylor", streakDays: 3, activeDays: 3 },
  ],
};
